import test from "node:test";
import assert from "node:assert/strict";
import { createDrishtiPlugin, normalizeAction } from "../src/index.js";

function installPlugin(config = {}) { let handler; createDrishtiPlugin({ config: { endpoint: "https://security.example/", agentId: "production-agent", credentialEnv: "DRISHTI_TEST_TOKEN", ...config }, on: (hook, fn) => { assert.equal(hook, "before_tool_call"); handler = fn; } }); return handler; }
function mockFetch(t, implementation) { const prior = global.fetch; global.fetch = implementation; t.after(() => { global.fetch = prior; }); }
const event = { toolName: "send_email", params: { to: "external@example.test", _drishti: { destination: "external" } }, runId: "run-1", toolCallId: "call-1" };
const ctx = { agentId: "openclaw-agent", sessionId: "session-1", runId: "run-1" };

test("normalizes the current OpenClaw 2026.9.5 hook shape", () => { const action = normalizeAction(event, ctx, { agentId: "production-agent" }); assert.equal(action.tool, "send_email"); assert.deepEqual(action.arguments.to, "external@example.test"); assert.equal(action.run_id, "run-1"); assert.equal(action.session_id, "session-1"); assert.equal(action.request_id, "call-1"); });
test("allows only an explicit backend ALLOW", async (t) => { process.env.DRISHTI_TEST_TOKEN = "secret"; mockFetch(t, async (url) => { assert.equal(url, "https://security.example/v1/actions/evaluate"); return new Response(JSON.stringify({ decision: "allow", request_id: "request-1" })); }); assert.equal(await installPlugin()(event, ctx), undefined); });
test("uses OpenClaw blockReason contract", async (t) => { process.env.DRISHTI_TEST_TOKEN = "secret"; mockFetch(t, async () => new Response(JSON.stringify({ decision: "block", reason: "unauthorized tool" }))); assert.deepEqual(await installPlugin()(event, ctx), { block: true, blockReason: "DRISHTI BLOCK: unauthorized tool" }); });
test("uses native requireApproval and approves only allow-once", async (t) => { process.env.DRISHTI_TEST_TOKEN = "secret"; const calls=[]; mockFetch(t, async (url) => { calls.push(url); return new Response(JSON.stringify({ decision: calls.length === 1 ? "review" : "allow", request_id: "review-1" })); }); const outcome = await installPlugin()(event, ctx); assert.deepEqual(outcome.requireApproval.allowedDecisions, ["allow-once", "deny"]); await outcome.requireApproval.onResolution("deny"); assert.equal(calls.length, 1); await outcome.requireApproval.onResolution("allow-once"); assert.match(calls[1], /\/v1\/actions\/review-1\/approve$/); });
test("fails closed when unavailable", async (t) => { process.env.DRISHTI_TEST_TOKEN = "secret"; mockFetch(t, async () => { throw new Error("offline"); }); const outcome = await installPlugin()(event, ctx); assert.equal(outcome.block, true); assert.match(outcome.blockReason, /unavailable/); });
